### ISSUE TITLE
There seems a bug in the codes.

### ISSUE THREAD

**Issue by jianxinss** [chemdemo/promiseA#2]
````
function resolvePromise(promise1, promise2) {
        var status = promise2.status;

        if('pending' === status) {
            promise2.then(promise1.resolve.bind(promise1), promise1.reject.bind(promise1));
        }
        if('resolved' === status) promise1.resolve(promise2.value);
        if('rejected' === status) promise1.reject(promise2.reason);

        return promise;
    };
````

the return value is undefined;

And what's more ,could you please explain the code to me. Because It seems hard to me . Thank u .

**Comment by chemdemo** [comment]
Thanks for point it out, and i had fixed it. It should return a promise too, see [here](https://github.com/chemdemo/promiseA/blob/master/lib/Promise.js#L187).

Will, for more detail about Promise/A+, you can read [the spec](https://github.com/promises-aplus/promises-spec).
